// ─── Doc Writer Skill Templates ────────────────────────────────────────────────

import type { SkillTemplate } from '../types'

export const DOC_WRITER_TEMPLATES: SkillTemplate[] = [

  {
    id: 'user-guide-generator',
    name: 'User Guide Generator',
    slug: 'user-guide-generator',
    description: 'Generate user guide / manual book ke Google Docs setiap deployment baru (FR-09)',
    agent: 'Agent 6 — Doc Writer',
    agentEmoji: '📝',
    category: 'Doc Writer',
    tags: ['docs', 'user-guide', 'google-docs', 'deployment', 'adlc'],
    content: `---
name: user-guide-generator
description: "WAJIB DIGUNAKAN: Ketika ada deployment baru ke Production, atau diminta membuat user guide, manual book, atau dokumentasi untuk end user."
---

# User Guide Generator Skill

Generate User Guide / Manual Book ke Google Docs setiap deployment baru (FR-09).

## Kapan Digunakan

- Deployment baru ke Production (trigger otomatis)
- User menyebut "buat user guide", "manual book", "dokumentasi user"
- Post-launch untuk setiap fitur baru

## Instruksi

### 1. Kumpulkan Input

Dari deployment yang baru:
- PRD final (problem + user stories + acceptance criteria)
- FSD (untuk understand technical flow)
- Prototype link (untuk screenshot/referensi visual)
- Changelog: apa yang berubah/ditambahkan?

### 2. Identifikasi Target Audience

- Siapa user-nya? (technical / non-technical)
- Bahasa yang digunakan: Indonesia (default) atau English?
- Platform: web / mobile / keduanya?

### 3. Susun User Guide

**Struktur:**

**1. Pendahuluan**
- Apa fitur ini?
- Siapa yang akan menggunakannya?
- Apa yang bisa dilakukan dengan fitur ini?

**2. Cara Menggunakan** (per user story)
Untuk setiap user story yang delivered:
- Step-by-step yang jelas (numbered list)
- Screenshot atau deskripsi visual di setiap step penting
- Tips dan catatan penting

**3. FAQ**
Pertanyaan yang kemungkinan muncul dari user:
- Q: [pertanyaan]
- A: [jawaban yang jelas dan singkat]

**4. Troubleshooting**
Masalah umum dan solusinya:
| Masalah | Kemungkinan Penyebab | Solusi |
|---------|---------------------|--------|
| [error/problem] | [penyebab] | [langkah solusi] |

**5. Kontak Support**
- Cara menghubungi support
- SLA response time

### 4. Simpan ke Google Docs

- Title: "User Guide - [Nama Fitur] - v[X.X] - [Tanggal]"
- Share ke stakeholder yang relevan

### 5. Kirim ke Users

Distribusikan via WhatsApp atau email ke users yang terdampak deployment ini.
`,
  },

  {
    id: 'compliance-reporter',
    name: 'Monthly Compliance Reporter',
    slug: 'compliance-reporter',
    description: 'Generate laporan compliance bulanan — FR-17 Audit Trail & Compliance',
    agent: 'Agent 6 — Doc Writer',
    agentEmoji: '📝',
    category: 'Doc Writer',
    tags: ['compliance', 'audit', 'monthly', 'fr-17', 'adlc'],
    content: `---
name: compliance-reporter
description: "WAJIB DIGUNAKAN: Pada heartbeat bulanan — generate laporan compliance yang merangkum semua keputusan AI yang berdampak ke produk dalam sebulan terakhir."
---

# Monthly Compliance Reporter Skill

Generate monthly compliance report yang merangkum aktivitas 6 agent ADLC (FR-17, Audit Trail & Compliance).

## Kapan Digunakan

- Heartbeat bulanan (tanggal 1 setiap bulan)
- User menyebut "compliance report", "laporan bulanan", "audit trail"
- CEO/Legal meminta audit summary

## Instruksi

### 1. Kumpulkan Data Bulan Lalu

Dari audit log (FR-17), kumpulkan:
- Semua PRD yang dibuat/di-approve
- Semua FSD yang dibuat/di-approve
- Deployment yang terjadi
- Bugs yang ditemukan dan diselesaikan
- Approval workflow yang dilalui (siapa approve apa, kapan)
- Cost per agent per fitur

### 2. Generate Laporan

---
**Monthly Compliance Report**
Period: [bulan] [tahun]
Generated: [tanggal generate]
Generated by: Agent 6 — Doc Writer

**1. Executive Summary**
- Total fitur yang diproses: [X]
- Total PRD dibuat: [X] | di-approve: [X] | rejected: [X]
- Total deployment ke Production: [X]
- Total bugs ditemukan: [X] | diselesaikan: [X]
- Total AI cost bulan ini: $[X]

**2. Agent Activity Summary**
| Agent | Runs | Success | Failed | Cost |
|-------|------|---------|--------|------|
| Agent 1 (PM/PA) | X | X | X | $X |
| Agent 2 (UX) | X | X | X | $X |
| Agent 3 (EM) | X | X | X | $X |
| Agent 4 (SWE) | X | X | X | $X |
| Agent 5 (QA) | X | X | X | $X |
| Agent 6 (Docs) | X | X | X | $X |

**3. Human Approval Log**
| Date | Agent | Document | Approved By | Notes |
|------|-------|----------|-------------|-------|
| [date] | Agent 1 | PRD - [fitur] | CPO | - |

**4. Quality Gates Status**
- Value Score coverage: [X/X PRD ada Value Score]
- Usability gate passed: [X/X prototype tested]
- QA coverage ≥ 80%: [X/X deployments]
- PII scan violations: [X incidents] | Resolved: [X]

**5. Data Privacy & Security**
- PII scan runs: [X]
- PII detected & masked: [X]
- Security incidents: [X]

**6. Compliance Status**
- ✅ GDPR: [status]
- ✅ SOC 2 Type II: [status]
- Audit log retention: [X months]
- Log export available: YES

**7. Incidents & Escalations**
[list incidents jika ada]
---

### 3. Simpan & Distribusikan

- Simpan ke Google Docs: "Compliance Report - [Bulan] [Tahun]"
- Kirim ke: CEO, CTO, CPO, Legal
`,
  },

]
