'use strict';
/**
 * sandbox-profile — generate macOS sandbox-exec (SBPL) profiles for per-user
 * gateway processes.
 *
 * Goal: hard-deny cross-tenant filesystem access at the kernel level. Even
 * if a model bypasses skill-based safety rules (aoc-safety-*) and tries to
 * `ls`/`cat` another tenant's directory, the OS will refuse with EPERM.
 *
 * Architecture:
 *   - Admin gateway (uid=1) is NOT sandboxed (runs via launchd directly).
 *   - Each per-user gateway (uid >= 2) is spawned as a child of
 *     `/usr/bin/sandbox-exec -f <profile> openclaw gateway`.
 *   - Profile is regenerated when peers are added/removed (post-provision
 *     hook in db.cjs and gateway-orchestrator.cjs).
 *
 * Caveats:
 *   - sandbox-exec is "deprecated" per Apple docs since macOS 10.10 but
 *     remains fully functional through macOS 15. If Apple removes it, switch
 *     to a libsandbox-based launcher.
 *   - Violations log to system.log; we also tee sandbox-exec stderr into
 *     <userHome>/logs/gateway.log for per-tenant audit.
 *   - Profile uses literal absolute paths because SBPL's regex matchers are
 *     limited; we generate the path list from SQLite at spawn time.
 */
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');

const OPENCLAW_BASE = process.env.OPENCLAW_HOME || path.join(os.homedir(), '.openclaw');

function _quote(s) {
  // SBPL strings use double quotes; escape backslashes and double quotes.
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

/**
 * Build an SBPL profile that denies cross-tenant filesystem access.
 *
 * @param {object} opts
 * @param {number} opts.ownerUserId — the user this gateway belongs to
 * @param {Array<number|string>} opts.peerUserIds — all OTHER user ids in the system
 * @param {string} [opts.openclawBase] — defaults to ~/.openclaw
 * @returns {string} SBPL profile content
 */
function buildSandboxProfile({ ownerUserId, peerUserIds, openclawBase = OPENCLAW_BASE }) {
  const ownerStr = String(ownerUserId);
  const peers = (peerUserIds || []).map(String).filter(id => id !== ownerStr);

  const denyCrossTenant = peers.map(uid =>
    `  (subpath ${_quote(path.join(openclawBase, 'users', uid))})`
  ).join('\n');

  // Admin-only secrets that no per-user gateway should be able to read.
  // These live at the openclawBase root (admin's home).
  const adminSecrets = [
    path.join(openclawBase, 'openclaw.json'),
    path.join(openclawBase, '.aoc_env'),
    path.join(openclawBase, 'exec-approvals.json'),
    path.join(openclawBase, 'exec-approvals.sock'),
  ].map(p => `  (literal ${_quote(p)})`).join('\n');

  const adminSecretDirs = [
    path.join(openclawBase, 'credentials'),
    path.join(openclawBase, 'identity'),
  ].map(p => `  (subpath ${_quote(p)})`).join('\n');

  // Backup files like openclaw.json.bak, openclaw.json.bak.1, etc.
  // SBPL regex is POSIX-ish; use a simple prefix match.
  const adminBackupRegex = `  (regex #${_quote('^' + openclawBase.replace(/[\\/]/g, '\\$&') + '/openclaw\\.json\\.bak')})`;

  return [
    '(version 1)',
    '; Auto-generated by AOC sandbox-profile.cjs',
    `; Owner: user ${ownerStr}; Peers denied: ${peers.length ? peers.join(', ') : '(none)'}`,
    '',
    '(allow default)',
    '',
    '; ── Cross-tenant deny ─────────────────────────────────────────────',
    '; Subpath blocks all read/write/list on a peer tenant tree, but does',
    '; NOT block file-read-metadata on the users/ parent dir — that would',
    '; break realpath() traversal needed by the gateway to access its own',
    '; workspace (every path component is stat-ed during canonicalization).',
    '; Peer existence remains observable via `ls users/`, but the content',
    '; is hard-denied — acceptable trade-off for kernel-enforced isolation.',
    peers.length ? '(deny file-read* file-write*' : '; (no peer tenants yet)',
    peers.length ? denyCrossTenant : '',
    peers.length ? ')' : '',
    '',
    '; ── Admin-only secrets ────────────────────────────────────────────',
    '(deny file-read* file-write*',
    adminSecrets,
    adminSecretDirs,
    adminBackupRegex,
    ')',
    '',
  ].filter(Boolean).join('\n');
}

/**
 * Write profile to disk and return its absolute path.
 */
function writeProfileForUser({ ownerUserId, peerUserIds, userHome, openclawBase = OPENCLAW_BASE }) {
  fs.mkdirSync(userHome, { recursive: true });
  const profile = buildSandboxProfile({ ownerUserId, peerUserIds, openclawBase });
  const file = path.join(userHome, '.sandbox-profile.sb');
  fs.writeFileSync(file, profile, { encoding: 'utf-8', mode: 0o600 });
  return file;
}

module.exports = {
  buildSandboxProfile,
  writeProfileForUser,
};
